name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Get the source
        uses: actions/checkout@v2
      - name: Restore the dependencies
        run: npm ci
      - name: Build with "npm run all"
        run: npm run all